version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:22.12.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci --only=production
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build React App
          command: |
            CI=false npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
            - package.json
            - package-lock.json

  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/node:22.12.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Netlify CLI
          command: npm install netlify-cli --no-save
      - run:
          name: Deploy to Netlify
          command: |
              ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=build

workflows:
  version: 2
  dev-release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
