name: Deploy to EC2

on:
  push:
    branches: [ "master" ]

env:
  EC2_HOST: 43.204.152.3                 # Replace with your EC2 instance's public IP
  EC2_USER: ubuntu                        # Replace with your EC2 instance's user (default is `ubuntu`)
  APP_NAME: adjerryproject               

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} << 'EOF'
        cd /home/ubuntu/${{ env.APP_NAME }}
        git pull
        npm install
        npm run build
        pm2 stop index || true
        pm2 start index
        pm2 save
        EOF
