name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

env:
  EC2_HOST: 13.126.127.43                 # Replace with your EC2 instance's public IP
  EC2_USER: ubuntu                        # Replace with your EC2 instance's user (default is `ubuntu`)
  APP_NAME: adjerryproject               

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        scp -r -o StrictHostKeyChecking=no . ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:/home/ubuntu/${{ env.APP_NAME }}

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} << 'EOF'
        cd /home/ubuntu/${{ env.APP_NAME }}
        npm install
        pm2 stop ${{ env.APP_NAME }} || true
        pm2 start ./bin/www --name ${{ env.APP_NAME }} --watch
        pm2 save
        EOF
